### ISSUE TITLE
Time data does not match format '%a, %d %b %Y %H:%M:%S'

### ISSUE THREAD

**Issue by fdegrave** [known-as-bmf/plugin.video.arteplussept#64] opened 2020-06-06 11:37 UTC
When trying to open some categories (not all of them) the plugin fails and the logs contain the following error:
```
2020-06-06 13:28:08.808 T:1380770528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: time data 'Tue, 23 Jun 2020 22:30:46' does not match format '%a, %d %b %Y %H:%M:%S'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.arteplussept/resources/lib/addon.py", line 111, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 342, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 316, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/plugin.video.arteplussept/resources/lib/addon.py", line 72, in sub_category_by_code
                                                return plugin.finish(view.build_sub_category_by_code(sub_category_code, language))
                                              File "/home/osmc/.kodi/addons/plugin.video.arteplussept/resources/lib/view.py", line 30, in build_sub_category_by_code
                                                return [mapper.map_generic_item(item) for item in api.subcategory(sub_category_code, lang)]
                                              File "/home/osmc/.kodi/addons/plugin.video.arteplussept/resources/lib/mapper.py", line 56, in map_generic_item
                                                return map_video(config)
                                              File "/home/osmc/.kodi/addons/plugin.video.arteplussept/resources/lib/mapper.py", line 68, in map_video
                                                airdate = str(utils.parse_date(airdate))
                                              File "/home/osmc/.kodi/addons/plugin.video.arteplussept/resources/lib/utils.py", line 40, in parse_date
                                                date = datetime.datetime.strptime(datestr, '%a, %d %b %Y %H:%M:%S')
                                              File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
                                                (data_string, format))
                                            ValueError: time data 'Tue, 23 Jun 2020 22:30:46' does not match format '%a, %d %b %Y %H:%M:%S'
                                            -->End of Python script error report<--
2020-06-06 13:28:09.153 T:1472193248   ERROR: GetDirectory - Error getting plugin://plugin.video.arteplussept/sub_category/SAN
```
This is quite strange, since I cannot reproduce the error using the local interpreter:

```
>>> import datetime
>>> date = datetime.datetime.strptime("Tue, 23 Jun 2020 22:30:46", '%a, %d %b %Y %H:%M:%S')
>>> date
datetime.datetime(2020, 6, 23, 22, 30, 46)
```
Any idea of the cause of this?

**Comment by hypnotoad** [comment] 2020-06-06 11:46
It is very probably a local problem. I have the same problem and would appreciate if it gets fixed. I don't know if kodi or the desktop environments sets the locale, but some action like this here needs to be carried out: https://stackoverflow.com/questions/18593661/how-do-i-strftime-a-date-object-in-a-different-locale

**Comment by fdegrave** [comment] 2020-06-06 14:26
You are indeed right! I fixed it doing this in resources/lib/utils.py (just added the part catching the ValueError):

```
import locale
import threading

def parse_date(datestr):
    # remove timezone info
    datestr = datestr[0:25]
    date = None
    # workaround for datetime.strptime not working (NoneType ???)
    try:
        date = datetime.datetime.strptime(datestr, '%a, %d %b %Y %H:%M:%S')
    except TypeError:
        date = datetime.datetime.fromtimestamp(time.mktime(
            time.strptime(datestr, '%a, %d %b %Y %H:%M:%S')))
    except ValueError:
        with threading.Lock():
            saved = locale.setlocale(locale.LC_ALL)
            locale.setlocale(locale.LC_ALL, "C")
            date = datetime.datetime.strptime(datestr, "%a, %d %b %Y %H:%M:%S")
            locale.setlocale(locale.LC_ALL, saved)
    return date
```

**Comment by fdegrave** [comment] 2020-06-06 14:31
Ouch, sometimes it still fails but on the line just above my code (in case of the TypeError). I should probably encapsulate the locale switch in a contextmanager.

**Comment by fdegrave** [comment] 2020-06-06 15:01
Not the cleanest code, but this seems to work all the time:

```python
import locale
import threading

def _parse_date(datestr):
    # remove timezone info
    datestr = datestr[0:25]
    date = None
    # workaround for datetime.strptime not working (NoneType ???)
    try:
        date = datetime.datetime.strptime(datestr, '%a, %d %b %Y %H:%M:%S')
    except TypeError:
        date = datetime.datetime.fromtimestamp(time.mktime(
            time.strptime(datestr, '%a, %d %b %Y %H:%M:%S')))
    return date

def parse_date(datestr):
    try:
        date = _parse_date(datestr)
    except ValueError:
        with threading.Lock():
            saved = locale.setlocale(locale.LC_ALL)
            locale.setlocale(locale.LC_ALL, "C")
            date = _parse_date(datestr)
            locale.setlocale(locale.LC_ALL, saved)
    return date
```

**Comment by hypnotoad** [comment] 2020-06-06 16:24
Looks quite good. If someone would be pedantic, one would mention that LC_TIME is not handled properly (LC_ALL overrides LC_TIME), but then it gets complicated and it was not even mentioned on stackexchange.

Now that you fixed this, I see that https://github.com/known-as-bmf/plugin.video.arteplussept/pull/57/commits/2073c4b84565292216d6c8300206c9ddb7e6cc70 is probably another fix for this problem :(

**Comment by hypnotoad** [comment] 2020-06-06 16:26
I would still create another pull request.

**Comment by fdegrave** [comment] 2020-06-06 18:44
Ah yeah right :-D I should have looked better before opening my code editor! And this PR looks prettier than my code, IMHO. Anyway, this fits me for now...

**Comment by SimonClavier** [comment] 2021-08-04 20:37
For information, I had this issue and upgrade to last version 1.1.2 manually ( following the [readme](https://github.com/known-as-bmf/plugin.video.arteplussept#readme)) and that solved the problem.
/!\ The official KODI repository is still in 1.1.1 !
It would be nice if this 1.1.2 could be included to the official KODI repository, sorry I didn't understand yet how to do it myself on the different KODI pages ...
- https://kodi.wiki/view/Add-on:Arte_%2B7
- https://kodi.wiki/view/Submitting_Add-ons
- https://kodi.wiki/view/Official_add-on_repository

**Comment by thomas-ernest** [comment] 2022-12-20 22:41
Hello @fdegrave ,

I understand the issue is fixed reading this thread. Is it ok to close the issue please ?

Thank you in advance,
Best regards,

**Closed** 2023-02-10 22:49 UTC
